import type { NextPage } from 'next';
import Head from 'next/head';
import { useTheme } from 'next-themes';
import { useEffect, useState } from 'react';
import { sanityClient } from 'lib/sanity-server';
import { postsQuery } from 'lib/queries';
import Container from 'components/Container';
import Image from 'next/image';
import BlogPostCard from 'components/BlogPostCard';
import Link from 'next/link';
import ProjectListItem from 'components/ProjectListItem';
import { FaReact, FaNode } from 'react-icons/fa';
import {
  SiTailwindcss,
  SiTypescript,
  SiStyledcomponents,
  SiMongodb,
} from 'react-icons/si';
import { TbBrandNextjs } from 'react-icons/tb';

const Home: NextPage = (props) => {
  const [mounted, setMounted] = useState(false);
  const { resolvedTheme, setTheme } = useTheme();

  // After mounting, we have access to the theme
  useEffect(() => setMounted(true), []);
  console.log(props);

  if (!mounted) {
    return null;
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="flex flex-col justify-center items-start max-w-4xl border-gray-200 dark:border-gray-700 mx-auto pb-16 px-6 md:px-14">
          <div className="flex flex-col-reverse sm:flex-row items-start">
            <div className="flex flex-col pr-8">
              <h1 className="font-bold text-3xl md:text-5xl tracking-wide mb-1 text-black dark:text-white">
                Kushal Raut
              </h1>
              <h2 className="text-gray-700 dark:text-gray-200 mb-4">
                Software Engineer at{' '}
                <span className="font-semibold">Kotuko</span>
              </h2>
              <p className="text-gray-600 dark:text-gray-400 mb-16">
                I am a software developer from Nepal.I work with React
                Ecosystem, and love sharing my developer experiences through my
                blogs.
              </p>
            </div>
            <div className="w-[80px]  sm:min-w-[176px]  relative mb-8 sm:mb-0 mr-auto">
              <Image
                alt="Kushal Raut"
                height={176}
                width={176}
                src="/kushal.jpg"
                sizes="30vw"
                priority
                className="rounded-full object-cover"
              />
            </div>
          </div>
          <h3 className="font-bold text-2xl md:text-4xl tracking-tight mb-6 text-black dark:text-white">
            Featured Posts
          </h3>
          <div className="flex gap-6 flex-col md:flex-row">
            <BlogPostCard
              title="Everything I Know About Style Guides, Design Systems, and Component Libraries"
              slug="style-guides-component-libraries-design-systems"
              gradient="from-[#D8B4FE] to-[#818CF8]"
            />
            <BlogPostCard
              title="Rust Is The Future of JavaScript Infrastructure"
              slug="rust"
              gradient="from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]"
            />
            <BlogPostCard
              title="Past, Present, and Future of React State Management"
              slug="react-state-management"
              gradient="from-[#FDE68A] via-[#FCA5A5] to-[#FECACA]"
            />
          </div>

          <Link href="/blog">
            <a className="flex mt-8 text-gray-600 dark:text-gray-400 leading-7 rounded-lg hover:text-gray-800 dark:hover:text-gray-200 transition-all h-6">
              Read all posts
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                className="h-6 w-6 ml-1"
              >
                <path
                  stroke="currentColor"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M17.5 12h-15m11.667-4l3.333 4-3.333-4zm3.333 4l-3.333 4 3.333-4z"
                />
              </svg>
            </a>
          </Link>

          <h3 className="font-bold text-2xl md:text-4xl tracking-tight mb-4 mt-16 text-black dark:text-white">
            Explore My Projects
          </h3>
          <p className="text-gray-600 dark:text-gray-400 mb-4">
            I love building side projects in my spare time which allows me to
            explore new frameworks and technologies
          </p>
          <ProjectListItem
            index="01"
            href="https://hoobank-kushal.vercel.app/"
            title="HooBank: The Next Generation Payment Method"
          >
            <FaReact />
            <SiTailwindcss />
          </ProjectListItem>
          <ProjectListItem
            index="02"
            href="https://cryptobanks.vercel.app/"
            title="Crypto Bank: A Decentralized Banking Platform"
          >
            <FaReact />
            <SiStyledcomponents />
          </ProjectListItem>
          <ProjectListItem
            index="03"
            href="https://shopitbykushal.herokuapp.com/"
            length="1:08:30"
            title="ShopIt: A Complete E-Commerce Platform"
          >
            <SiMongodb />
            <FaReact />
            <FaNode />
          </ProjectListItem>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.youtube.com/playlist?list=PL6bwFJ82M6FXgctyoWXqj7H0GK8_YIeF1"
            className="flex mt-8 text-gray-600 dark:text-gray-400 leading-7 rounded-lg hover:text-gray-800 dark:hover:text-gray-200 transition-all h-6"
          >
            See all projects
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              className="h-6 w-6 ml-1"
            >
              <path
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M17.5 12h-15m11.667-4l3.333 4-3.333-4zm3.333 4l-3.333 4 3.333-4z"
              />
            </svg>
          </a>
        </div>
      </Container>
    </div>
  );
};

export default Home;

export const getServerSideProps: any = async () => {
  const posts = await sanityClient.fetch(postsQuery);

  return {
    props: {
      posts,
    },
  };
};
