import type { NextPage } from 'next';
import Head from 'next/head';
import useAppDispatch from '../hooks/useAppDispatch';
import useAppSelector from '../hooks/useAppSelector';
import { setTheme } from '../redux/theme/themeSlice';

const Home: NextPage = () => {
  const { current } = useAppSelector((state) => state.theme);
  const dispatch = useAppDispatch();
  console.log(current);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white text-black dark:bg-black dark:text-white">
        <button
          onClick={() => {
            dispatch(setTheme('light'));
          }}
        >
          Change Theme
        </button>
      </div>
    </div>
  );
};

export default Home;
